version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.4
jobs:
  build_server:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo/server
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - server-modules-{{ checksum "package-lock.json" }}

      # check npm dependencies for security risks - run 'npm audit' to fix
      - run: npx audit-ci --high --report-type full

      # install dependencies
      - run: npm ci

      - save_cache:
          key: server-modules-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm

      # ensure code formatting standards are adhered to - run 'npm run style:fix' to fix
      - run: npm run style
      - run: npm run lint

      # run tests and store test results
      - run: npm run pretest
      - run: npm run test:ci
      - store_test_results:
          path: ./test_results

      # run code coverage and store coverage report
      - run: npm run test:nyc
      - store_artifacts:
          path: ./coverage

      - coveralls/upload

      - run:
          name: Move compiled app to workspace
          command: |
            set -exu
            mkdir -p /tmp/workspace/server
            mv dist /tmp/workspace/server
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - server

  build_webapp:
    docker:
      - image: circleci/node:lts-browsers
    working_directory: ~/repo/web-app
    steps:
      - checkout:
          path: ~/repo
      - run: cd ..; npm run modules:init
      - restore_cache:
          keys:
            - web-modules-{{ checksum "package-lock.json" }}

      - run: npm ci
      - run: npx ngcc --properties es2015

      - save_cache:
          key: web-modules-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm

      - run: npm run style
      - run: npm run lint
      - run: npm run build -- --configuration=lemon-mart-server
      - run: npm test -- --watch=false --code-coverage

      - store_test_results:
          path: ./test_results
      - store_artifacts:
          path: ./coverage

      - run:
          name: Tar & Gzip compiled app
          command: tar zcf dist.tar.gz dist/lemon-mart
      - store_artifacts:
          path: dist.tar.gz

      - run:
          name: Move compiled app to workspace
          command: |
            set -exu
            mkdir -p /tmp/workspace/dist
            mv dist/lemon-mart /tmp/workspace/dist/
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - dist/lemon-mart

workflows:
  version: 2
  build-server-and-webapp:
    jobs:
      - build_server
      - build_webapp

